# Generated by Django 4.2.1 on 2023-05-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_employee_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_admin',
            new_name='is_supervisor',
        ),
    ]
