# Generated by Django 4.2.1 on 2023-05-12 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assays',
            field=models.JSONField(default={'test1': {'lot_numbers': ['1A111'], 'num_tests': 1}, 'test2': {'lot_numbers': [], 'num_tests': 0}, 'test3': {'lot_numbers': ['3A333', '3B333'], 'num_tests': 2}}),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
