# Generated by Django 4.2.1 on 2023-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_assays_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assays',
            field=models.JSONField(default={'test1': {'lot_numbers': [], 'num_tests': 0}, 'test2': {'lot_numbers': [], 'num_tests': 0}, 'test3': {'lot_numbers': [], 'num_tests': 0}}),
        ),
    ]
