# Generated by Django 4.2.1 on 2023-05-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderassay',
            unique_together=set(),
        ),
    ]
