# Generated by Django 4.2.1 on 2023-05-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assay_result_assay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELISA',
            fields=[
                ('assay_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.assay')),
            ],
            bases=('core.assay',),
        ),
        migrations.CreateModel(
            name='PCR',
            fields=[
                ('assay_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.assay')),
            ],
            bases=('core.assay',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='assays',
        ),
        migrations.AddField(
            model_name='order',
            name='assays',
            field=models.CharField(choices=[('PCR', 'PCR'), ('ELISA', 'ELIZA'), ('Other', 'OTHER')], default='', max_length=10, verbose_name='Assay'),
            preserve_default=False,
        ),
    ]
